<?php require './app/templates/header.phtml' ?>

<!-- artistDetail.php -->
<div>
    <h2><?= $artist->name ?></h2>
    <p><?= $artist->biography ?></p>
    <h3><a href="songsByArtist/<?= $artist->id_artist ?>">Ver canciones de <?= $artist->name ?></a></h3>
</div>

<!-- IF SESSION MOSTRAMOS FORMULARIO DE EDITAR O BOTON DE BORRAR -->
<?php //if ($this->session) : 
?>

<form action="editArtistForm/<?= $artist->id_artist ?>">
    <button type="submit">Editar</button>
</form>
<form action="removeArtist/<?= $artist->id_artist ?>">
    <button type="submit" onclick="return confirm('¿Estás seguro de que queres borrar este artista?');">Borrar</button>
</form>
<?php //endif 
?>


<h4><a href="artists">Volver al listado de Artistas</a></h4>

<?php require './app/templates/footer.phtml' ?>