<!-- formArtist.phtml -->
<div>
    <label>Nombre
        <input required name="name" type="text" value="<?= $artist->name ?? ''   ?>">
    </label>

    <label>Biografia
        <input required name="biography" type="text" value="<?= $artist->biography ?? ''  ?>">
    </label>

    <label>Imagen <!-- No tiene required -->
        <input name="input_name" type="file" value="<?= $artist->image ?? ''  ?>">
    </label>
</div>