<div>
    <p>Si querés agregar una canción, primero tiene que existir un artista.</p>
    <p>Si no podés encontrar al artista que querés, <a href='addArtistForm/'>agrega el artista!</a></p>

    <label> Artista
        <select required name="id_artist">
            <option disabled <?= !isset($song) ? 'selected' : '' ?>>De qué artista es la canción?</option>
            <?php foreach ($artists as $artist) : ?>
                <option value="<?= $artist->id_artist ?>"
                    <?= isset($song) && $artist->id_artist == $song->id_artist ? 'selected' : '' ?>>
                    <?= $artist->name ?>
                </option>
            <?php endforeach ?>
        </select>
    </label>

    <label> Título
        <input required name="title" type="text" value="<?= $song->title ?? '' ?>">
    </label>

    <label> Álbum
        <input required name="album" type="text" value="<?= $song->album ?? '' ?>">
    </label>

    <label> Duración
        <small>La duración se indica en minutos y dos decimales, por ejemplo 3.55</small>
        <input required name="duration" type="number" step="0.01" value="<?= $song->duration ?? '' ?>">
    </label>

    <label> Género
        <input required name="genre" type="text" value="<?= $song->genre ?? '' ?>">
    </label>

    <label> Link al Video
        <input required name="video" type="text" value="<?= $song->video ?? '' ?>">
    </label>
</div>