<!DOCTYPE html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <base href="<?= BASE_URL ?>">
    <link rel="stylesheet" href="css/styles.css">
    <title>SoundSnack</title>
    <!-- podria agregar la variable $title en cada funcion del view para que vaya cambiando ! -->
</head>

<body>
    <!-- HEADER -->
    <header>

        <?php if (AuthHelper::check()) : ?><h4>Sesión iniciada</h4><?php endif; ?>
        <!-- NAV -->
        <nav>

            <!-- Public Access -->
            <li><a href="songs">Canciones</a></li>
            <li><a href="artists">Artistas</a></li>

            <!-- Admin Access -->
            <?php if ($this->session) : ?>
                <li>
                    <a href="logout">Logout</a>
                </li>
            <?php else : ?>
                <li>
                    <a href="login">Login</a>
                </li>
            <?php endif; ?>

        </nav>
    </header>
</body>